import { StyleSheet } from 'react-native';
import { responsiveFontSize } from '../utils/responsive';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  controls: {
    paddingHorizontal: 29,
    paddingBottom: 45,
    zIndex: 10,
  },
  dropdownContainer: {
    marginBottom: 15,
    backgroundColor: '#fff',
    borderRadius: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#eee',
    overflow: 'hidden',
  },
  dropdownHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14,
    backgroundColor: '#fff',
    borderRadius: 4,
  },
  dropdownLabel: {
    fontSize: responsiveFontSize(16),
    fontWeight: '600',
    color: '#000000',
  },
  chevron: {
    fontSize: responsiveFontSize(12),
    color: '#333',
  },
  dropdownList: {
    backgroundColor: '#fff',
    borderTopColor: '#eee',
    borderTopWidth: 1,
    paddingVertical: 20,
    paddingHorizontal: 18,
  },
  dropdownItem: {
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    borderRadius: 6,
    backgroundColor: '#f5f5f5',
  },
  dropdownItemActive: {
    backgroundColor: '#00B4E4',
  },
  dropdownItemText: {
    fontSize: responsiveFontSize(14),
    color: '#000000',
  },
  dropdownItemTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  input: {
    height: 50,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#E3E3E3',
    borderRadius: 5,
    padding: 12,
    fontSize: responsiveFontSize(16),
    marginBottom: 16,
    fontWeight: '600',
    color: '#999999',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  searchButton: {
    backgroundColor: '#e0e0e0',
    borderRadius: 25,
    paddingVertical: 14,
    alignItems: 'center',
  },
  searchButtonText: {
    color: '#666',
    fontWeight: '600',
    fontSize: responsiveFontSize(16),
  },
  listContainer: {
    flex: 1,
  },
  listContent: {
    padding: 20,
  },
  card: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E3E3E3',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    height: 160,
  },
  poster: {
    width: 106,
    height: '100%',
    backgroundColor: '#ddd',
  },
  cardContent: {
    flex: 1,
    padding: 14,
    justifyContent: 'flex-start',
  },
  movieTitle: {
    fontSize: responsiveFontSize(16),
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 4,
  },
  movieDate: {
    fontSize: responsiveFontSize(12),
    color: '#999',
    marginBottom: 12,
  },
  movieOverview: {
    fontSize: responsiveFontSize(13),
    color: '#333',
    lineHeight: 18,
  },
  footer: {
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadMoreButton: {
    width: '100%',
    backgroundColor: '#01b4e4',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 5,
    alignItems: 'center',
  },
  loadMoreText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: responsiveFontSize(20),
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    marginTop: 50,
  },
  emptyText: {
    fontSize: responsiveFontSize(16),
    color: '#666',
    textAlign: 'center',
    marginTop: 10,
  },
  errorContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorText: {
    color: 'red',
    fontSize: responsiveFontSize(16),
    textAlign: 'center',
    marginBottom: 10,
  },
  retryButton: {
    backgroundColor: '#01b4e4',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 5,
  },
  retryText: {
    color: '#fff',
    fontWeight: '600',
  },
});
